### ISSUE TITLE
I'm guessing a speaker is required...

### ISSUE THREAD

**Issue by OutsourcedGuru** [MoonshineSG/OctoPrint-Sound#1]
The documentation doesn't seem to mention how the sound is produced and where.  I might assume server-side (on the Raspberry Pi 3 inside the printer) but since we're talking about an OctoPrint (web app) modification, that could technically mean that the sound is streamed back to the browser on the client.

Assuming server-side for a moment, then the next guess is that an 1/8" mono or stereo plug is inserted into the Raspberry Pi 3's audio jack.  (Sometimes there are issues with the audio and PWM competing for resources but since you have something working with yours, I'll guess this isn't the case.)

So... it would be nice if your README mentioned how the sound is played and what modifications are necessary.  Thanks.

**Comment by MoonshineSG** [comment]
I thought its quite obvious... since it's supposed to "replace printer sounds [...] played by RPi"  
The sounds is coming on the audio jack via a speaker (either active speaker or over a small amp)
