### ISSUE TITLE
No Sound, keeps defaulting to default.mp3. 

### ISSUE THREAD

**Issue by alvinlsx** [MoonshineSG/OctoPrint-Sound#6]
Hi, I've successfully installed **1.0.6** with no errors. However, I am unable to get any sound out of the 3.5mm jack.

I've placed some mp3 files inside _.octoprint/data/sound_ and _.octoprint/plugins/sound_, all of which have the following mp3 files in 128kbps:
- default.mp3 (86kb)
- startup.mp3 (96kb)

Upon calling `m300 @startup` , the console shows m300 @STARTUP and plays the default.mp3 file with no sound. I realized that no matter what @keyword is inserted into the console, it becomes uppercase. It also doesn't seem to be able to find the startup.mp3 file inside .octoprint/data/sound.

Things I've tried:
- Reinstalling the plugin
- Rebooting the Pi
- SSH-ing into the pi and trying  `speaker-test -t wav -c 6` (There is sound, albeit rather soft)

Octoprint Version: 1.7.1 (Correction: It is 1.7.2)
OctoPi Version: 0.18.0

PS: Thanks for taking the time out to develop this plugin

**Comment by MoonshineSG** [comment]
Can you have a look at the logs to see if there's any error or message related to the plugin ? 

The capitalisation of the keyword is strange. Is that a "feature" of your OS on the notebook/desktop/tablet you're using ?

**Comment by alvinlsx** [comment]
Install logs look good to me:
[plugin_pluginmanager_console.log](https://github.com/MoonshineSG/OctoPrint-Sound/files/7805550/plugin_pluginmanager_console.log)

And this is the octoprint.log with the following logging levels enabled:
![image](https://user-images.githubusercontent.com/40485660/148015958-28f38a68-34d1-4cc9-aa3d-4af78d94fd16.png)
[octoprint.log](https://github.com/MoonshineSG/OctoPrint-Sound/files/7805623/octoprint.log)

I've tried to repeatedly trigger `m300 @startup or m300 @default` to see if anything will show up in the logs but I don't see anything. Perhaps my logging settings are wrong?

This is what I meant by the capitalization, not sure if this is normal behavior but I've tried it on my phone too and another computer, they all behave similarly:
`m300 @startup` shows up as `(@STARTUP)`

![1](https://user-images.githubusercontent.com/40485660/148014184-6cee1f5b-05cd-405c-800d-4934b770dd3a.png)

And this is how the folders look like:
![image](https://user-images.githubusercontent.com/40485660/148014444-10360dca-e829-4e3d-8b09-b0ba1dc68324.png)

**Comment by MoonshineSG** [comment]
I see... 
I have gave up on 3D printing and I don't have any way to test this... But ... My guess is that some change in recent Octoprint version capitalises the parameters of commands... YOU can test my theory by renaming one of the files to capital letters (eg DEFAULT.mp3 or DEFAULT.MP3) If that works you rename them all and you're good. If not, I'll carry on thinking :D 

Let me know.

**Comment by MoonshineSG** [comment]
Whoops.... Notice this in the logs 
``` py.warnings - WARNING - /home/pi/oprint/lib/python3.7/site-packages/octoprint_sound/__init__.py:27: RuntimeWarning: use mixer: libSDL2_mixer-2.0.so.0: cannot open shared object file: No such file or directory
(ImportError: libSDL2_mixer-2.0.so.0: cannot open shared object file: No such file or directory)
  if not pygame.mixer.get_init():
```

That means your ` pygame` is not properly installed or missing the library...

**Comment by alvinlsx** [comment]
Whelp, good catch on that error, totally missed it. I tried doing a `sudo apt-get install python-pygame` via ssh and rebooted the pi but the error still persists. Currently looking to ways to fix this. 

I also did a `amixer -q -M sset Headphone 80%` and `sudo alsactl store` to make sure the 3.5mm jack is outputting audible levels of audio which worked so far (installed sox and used `play foo.mp3` to test the files and the 3.5mm jack, both are working)

Once the pygame error is fixed and it still doesn't work, I'm going to try renaming the files to capital letters just to give it a shot.

Will update shortly, thanks for the help so far man.

**Comment by MoonshineSG** [comment]
try  `apt-get install libsdl2-mixer-2.0-0`

**Comment by alvinlsx** [comment]
Yep, I've tried that as well (saw it from: https://github.com/cosmologicon/pygame-text/issues/7)
Still getting this:

```
 2022-01-04 14:59:55,353 - py.warnings - WARNING - /home/pi/oprint/lib/python3.7/site-packages/octoprint_sound/__init__.py:27: RuntimeWarning: use mixer: libSDL2_mixer-2.0.so.0: cannot open shared object file: No such file or directory
(ImportError: libSDL2_mixer-2.0.so.0: cannot open shared object file: No such file or directory)
  if not pygame.mixer.get_init():
```

**Comment by MoonshineSG** [comment]
just checking... did you install `pygame` for python3 ? (`pip3 install pygame`) ...

**Comment by alvinlsx** [comment]
Yep, I did. I had to install pip first though because it wasn't part of OctoPi. Pygame and libsdl2-mixer-2.0-0 are both installed. 
<img width="531" alt="image" src="https://user-images.githubusercontent.com/40485660/148024263-85e494c9-756a-42c4-9390-b4f14371b271.png">

I ran a `sudo apt-update --fix-missing` as well. Issue still persist with the same error.

**Comment by MoonshineSG** [comment]
I'm not sure how I can help. Try to find smth to fix pygame or feel free to change the MP3 player if you're ok with coding in python...

**Comment by MoonshineSG** [comment]
one more thing.. try to find if "libSDL2_mixer-2.0.so.0" is really on your system... maybe it's a version conflict...

**Comment by alvinlsx** [comment]
No worries, I'll mess around a little further and see if I can get it to work and update you if it does (and perhaps post a solution if I found one). 

Thanks for your help!

**Comment by alvinlsx** [comment]
I managed to fix the dependency error and it is now working.

At first `apt-get install libsdl2-mixer-2.0-0` did not work and was constantly giving a 404, which I then ran an `sudo apt-update` which didn't work either as it required some permissions to be accepted manually.

What fixed it was:

1. `sudo apt update` and manually accept all permission prompts (just press "y" all the way)
2. `apt-get install libsdl2-mixer-2.0-0` will work and no longer results in a 404
3. Reboot and try m300 again


On top of that, to ensure volume isn't defaulted at 40% on boot:
`amixer -q -M sset Headphone 80%` and `sudo alsactl store`

Edit: I think your plugin already sets the volume at 100 by default, whoops
![image](https://user-images.githubusercontent.com/40485660/148180192-a6dabde9-cc8f-467c-b1e9-9b29e3515eb5.png)



The only issue I am trying to fix now is that m300 @"something" keeps calling default.mp3, but there is sound now.

**Comment by MoonshineSG** [comment]
awesome!

maybe that can be solved by capitalising the file names... 🤞🏻

**Comment by alvinlsx** [comment]
> awesome! maybe that can be solved by capitalising the file names... 🤞🏻
> […](#)
> On 5 Jan 2022, at 15:44, Alvin Lim ***@***.***> wrote: ﻿ I managed to fix the dependency error and it is now working. At first apt-get install libsdl2-mixer-2.0-0 did not work and was constantly giving a 404, which I then ran an sudo apt-update which didn't work either as it required some permissions to be accepted manually. What fixed it was: sudo apt update and manually accept all permission prompts (just press "y" all the way) apt-get install libsdl2-mixer-2.0-0 will work and no longer results in a 404 Reboot and try m300 again On top of that, to ensure volume isn't defaulted at 40% on boot: amixer -q -M sset Headphone 80% and sudo alsactl store The only issue I am trying to fix now is that m300 @"something" keeps calling default.mp3, but there is sound now. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.

You are absolutely right. That fixed it:
![image](https://user-images.githubusercontent.com/40485660/148181757-5e04aea9-ba73-4d8a-8638-2bb4779bc80e.png)

![image](https://user-images.githubusercontent.com/40485660/148181706-5b3f58c3-8edb-40ab-9bdb-935bf115e4cc.png)

Thanks again!

**Comment by MoonshineSG** [comment]
Good to hear that!  It must be a change in latest Octoprint... 

Happy printing!!!

**Comment by alvinlsx** [comment]
Sorry to necro this thread again but:

I realized that if I were to send an `m300 @default` directly into the terminal, it would work. But placing them in the start GCODE section yields an unknown command error and no sound is played

![image](https://user-images.githubusercontent.com/40485660/148200693-3575e7fa-de41-4b8c-94dd-e6dd6b37c559.png)

**Comment by MoonshineSG** [comment]
try capital M ? `M300 @WHATEVER`
